// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.V0.V0.Users.Collections.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.V0.V0.Users.Collections
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\users\-\collections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CollectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The minus property</summary>
        public global::BangumiNet.Api.V0.V0.Users.Collections.Minus_RequestBuilder Minus
        {
            get => new global::BangumiNet.Api.V0.V0.Users.Collections.Minus_RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BangumiNet.Api.V0.v0.users.collections.item collection</summary>
        /// <param name="position">条目 ID</param>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder"/></returns>
        public global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("subject_id", position);
                return new global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BangumiNet.Api.V0.v0.users.collections.item collection</summary>
        /// <param name="position">条目 ID</param>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("subject_id", position);
                return new global::BangumiNet.Api.V0.V0.Users.Collections.Item.WithSubject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/-/collections", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/-/collections", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
