// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Subjects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubjectsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The infobox property</summary>
        public string? Infobox { get; set; }
        /// <summary>The metaTags property</summary>
        public List<string>? MetaTags { get; set; }
        /// <summary>The name property</summary>
        public string? Name { get; set; }
        /// <summary>The nsfw property</summary>
        public bool? Nsfw { get; set; }
        /// <summary>The platform property</summary>
        public int? Platform { get; set; }
        /// <summary>The series property</summary>
        public bool? Series { get; set; }
        /// <summary>The summary property</summary>
        public string? Summary { get; set; }
        /// <summary>条目类型  - 1 = 书籍  - 2 = 动画  - 3 = 音乐  - 4 = 游戏  - 6 = 三次元  没有 5</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Subjects.SubjectsPostRequestBody"/> and sets the default values.
        /// </summary>
        public SubjectsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Wiki.Subjects.SubjectsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.P1.Wiki.Subjects.SubjectsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.P1.Wiki.Subjects.SubjectsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "infobox", n => { Infobox = n.GetStringValue(); } },
                { "metaTags", n => { MetaTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nsfw", n => { Nsfw = n.GetBoolValue(); } },
                { "platform", n => { Platform = n.GetIntValue(); } },
                { "series", n => { Series = n.GetBoolValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("infobox", Infobox);
            writer.WriteCollectionOfPrimitiveValues<string>("metaTags", MetaTags);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("nsfw", Nsfw);
            writer.WriteIntValue("platform", Platform);
            writer.WriteBoolValue("series", Series);
            writer.WriteStringValue("summary", Summary);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
