// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.Models;
using BangumiNet.Api.P1.P1.Users.Item.Blogs;
using BangumiNet.Api.P1.P1.Users.Item.Collections;
using BangumiNet.Api.P1.P1.Users.Item.Followers;
using BangumiNet.Api.P1.P1.Users.Item.Friends;
using BangumiNet.Api.P1.P1.Users.Item.Groups;
using BangumiNet.Api.P1.P1.Users.Item.Indexes;
using BangumiNet.Api.P1.P1.Users.Item.Timeline;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.P1.P1.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\users\{username}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUsernameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blogs property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Blogs.BlogsRequestBuilder Blogs
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Blogs.BlogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collections property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The followers property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Followers.FollowersRequestBuilder Followers
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The friends property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Friends.FriendsRequestBuilder Friends
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Friends.FriendsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Groups.GroupsRequestBuilder Groups
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexes property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Indexes.IndexesRequestBuilder Indexes
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Indexes.IndexesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timeline property</summary>
        public global::BangumiNet.Api.P1.P1.Users.Item.Timeline.TimelineRequestBuilder Timeline
        {
            get => new global::BangumiNet.Api.P1.P1.Users.Item.Timeline.TimelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Users.Item.WithUsernameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUsernameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/users/{username}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Users.Item.WithUsernameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUsernameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/users/{username}", rawUrl)
        {
        }
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.User"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::BangumiNet.Api.P1.Models.User?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.P1.Models.User>(requestInfo, global::BangumiNet.Api.P1.Models.User.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Users.Item.WithUsernameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.P1.P1.Users.Item.WithUsernameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.P1.P1.Users.Item.WithUsernameItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
