// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoversGetResponse_covers : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers_creator? Creator { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers_creator Creator { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Raw { get; set; }
#nullable restore
#else
        public string Raw { get; set; }
#endif
        /// <summary>The thumbnail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thumbnail { get; set; }
#nullable restore
#else
        public string Thumbnail { get; set; }
#endif
        /// <summary>The voted property</summary>
        public bool? Voted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers"/> and sets the default values.
        /// </summary>
        public CoversGetResponse_covers()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creator", n => { Creator = n.GetObjectValue<global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers_creator>(global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers_creator.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "raw", n => { Raw = n.GetStringValue(); } },
                { "thumbnail", n => { Thumbnail = n.GetStringValue(); } },
                { "voted", n => { Voted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Covers.CoversGetResponse_covers_creator>("creator", Creator);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("raw", Raw);
            writer.WriteStringValue("thumbnail", Thumbnail);
            writer.WriteBoolValue("voted", Voted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
