// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.V0.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.V0.V0.Search.Persons
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\search\persons
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PersonsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/search/persons{?limit*,offset*}", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/search/persons{?limit*,offset*}", rawUrl)
        {
        }

        /// <summary>
        /// ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动目前支持的筛选条件包括:- `career`: 职业，可以多次出现。`且` 关系。不同筛选条件之间为 `且`
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.Paged_Person"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public async Task<global::BangumiNet.Api.V0.Models.Paged_Person?> PostAsync(global::BangumiNet.Api.V0.V0.Search.Persons.PersonsPostRequestBody body, Action<RequestConfiguration<global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder.PersonsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.V0.Models.Paged_Person>(requestInfo, global::BangumiNet.Api.V0.Models.Paged_Person.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动目前支持的筛选条件包括:- `career`: 职业，可以多次出现。`且` 关系。不同筛选条件之间为 `且`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPostRequestInformation(global::BangumiNet.Api.V0.V0.Search.Persons.PersonsPostRequestBody body, Action<RequestConfiguration<global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder.PersonsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }

        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.V0.V0.Search.Persons.PersonsRequestBuilder(rawUrl, RequestAdapter);
        }

        /// <summary>
        /// ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动目前支持的筛选条件包括:- `career`: 职业，可以多次出现。`且` 关系。不同筛选条件之间为 `且`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PersonsRequestBuilderPostQueryParameters 
        {
            /// <summary>分页参数</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }

            /// <summary>分页参数</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
        }
    }
}
#pragma warning restore CS0618
