// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.P1.P1.Persons.Item.Works
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\persons\{personID}\works
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/persons/{personID}/works{?limit*,offset*,position*,subjectType*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/persons/{personID}/works{?limit*,offset*,position*,subjectType*}", rawUrl)
        {
        }
        /// <summary>
        /// 获取人物的参与作品
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksGetResponse?> GetAsync(Action<RequestConfiguration<global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder.WorksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksGetResponse>(requestInfo, global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取人物的参与作品
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder.WorksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.P1.P1.Persons.Item.Works.WorksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 获取人物的参与作品
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorksRequestBuilderGetQueryParameters 
        {
            /// <summary>max 100</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>min 0</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>职位</summary>
            [QueryParameter("position")]
            public int? Position { get; set; }
            [QueryParameter("subjectType")]
            public int? SubjectType { get; set; }
        }
    }
}
#pragma warning restore CS0618
