// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.V0.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.V0.V0.Users.Item.Collections.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\users\{username}\collections\{subject_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSubject_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Item.Collections.Item.WithSubject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubject_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/{username}/collections/{subject_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Item.Collections.Item.WithSubject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubject_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/{username}/collections/{subject_id}", rawUrl)
        {
        }
        /// <summary>
        /// 获取对应用户的收藏，查看私有收藏需要 access token
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.UserSubjectCollection"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BangumiNet.Api.V0.Models.ErrorDetail">When receiving a 400 status code</exception>
        /// <exception cref="global::BangumiNet.Api.V0.Models.ErrorDetail">When receiving a 404 status code</exception>
        public async Task<global::BangumiNet.Api.V0.Models.UserSubjectCollection?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::BangumiNet.Api.V0.Models.ErrorDetail.CreateFromDiscriminatorValue },
                { "404", global::BangumiNet.Api.V0.Models.ErrorDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.V0.Models.UserSubjectCollection>(requestInfo, global::BangumiNet.Api.V0.Models.UserSubjectCollection.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取对应用户的收藏，查看私有收藏需要 access token
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Users.Item.Collections.Item.WithSubject_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.V0.V0.Users.Item.Collections.Item.WithSubject_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.V0.V0.Users.Item.Collections.Item.WithSubject_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
