// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Wiki.Recent.Characters;
using BangumiNet.Api.P1.P1.Wiki.Recent.Episodes;
using BangumiNet.Api.P1.P1.Wiki.Recent.Persons;
using BangumiNet.Api.P1.P1.Wiki.Recent.Subjects;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Recent
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\wiki\recent
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecentRequestBuilder : BaseRequestBuilder
    {

        public global::BangumiNet.Api.P1.P1.Wiki.Recent.Characters.CharactersRequestBuilder Characters
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Recent.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }

        public global::BangumiNet.Api.P1.P1.Wiki.Recent.Episodes.EpisodesRequestBuilder Episodes
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Recent.Episodes.EpisodesRequestBuilder(PathParameters, RequestAdapter);
        }

        public global::BangumiNet.Api.P1.P1.Wiki.Recent.Persons.PersonsRequestBuilder Persons
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Recent.Persons.PersonsRequestBuilder(PathParameters, RequestAdapter);
        }

        public global::BangumiNet.Api.P1.P1.Wiki.Recent.Subjects.SubjectsRequestBuilder Subjects
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Recent.Subjects.SubjectsRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Recent.RecentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/recent", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Recent.RecentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/recent", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
