// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Persons;
using BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Positions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Subjects.Item.Staffs
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\subjects\{subjectID}\staffs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StaffsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The persons property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Persons.PersonsRequestBuilder Persons
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Persons.PersonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The positions property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Positions.PositionsRequestBuilder Positions
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.Positions.PositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.StaffsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaffsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/{subjectID}/staffs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.StaffsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaffsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/{subjectID}/staffs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
