// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Ep
{
    [Obsolete("This class is obsolete. Use EpPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EpResponse : global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Ep.EpPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Ep.EpResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Ep.EpResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.P1.Wiki.Subjects.Item.Ep.EpResponse();
        }
    }
}
#pragma warning restore CS0618
