// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Wiki.Lock.Subjects;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Lock
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\wiki\lock
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LockRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The subjects property</summary>
        public global::BangumiNet.Api.P1.P1.Wiki.Lock.Subjects.SubjectsRequestBuilder Subjects
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Lock.Subjects.SubjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Lock.LockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LockRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/lock", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Lock.LockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LockRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/lock", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
