// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.P1.Models;
using BangumiNet.Api.P1.P1.Subjects.Item.Characters;
using BangumiNet.Api.P1.P1.Subjects.Item.Collects;
using BangumiNet.Api.P1.P1.Subjects.Item.Comments;
using BangumiNet.Api.P1.P1.Subjects.Item.Episodes;
using BangumiNet.Api.P1.P1.Subjects.Item.Indexes;
using BangumiNet.Api.P1.P1.Subjects.Item.Recs;
using BangumiNet.Api.P1.P1.Subjects.Item.Relations;
using BangumiNet.Api.P1.P1.Subjects.Item.Reviews;
using BangumiNet.Api.P1.P1.Subjects.Item.Staffs;
using BangumiNet.Api.P1.P1.Subjects.Item.Topics;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.P1.P1.Subjects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\subjects\{subjectID}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSubjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The characters property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Characters.CharactersRequestBuilder Characters
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collects property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Collects.CollectsRequestBuilder Collects
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Collects.CollectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comments property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Comments.CommentsRequestBuilder Comments
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episodes property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Episodes.EpisodesRequestBuilder Episodes
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Episodes.EpisodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexes property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Indexes.IndexesRequestBuilder Indexes
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Indexes.IndexesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recs property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Recs.RecsRequestBuilder Recs
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Recs.RecsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The relations property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Relations.RelationsRequestBuilder Relations
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Relations.RelationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reviews property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Reviews.ReviewsRequestBuilder Reviews
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Reviews.ReviewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The staffs property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.StaffsRequestBuilder Staffs
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Staffs.StaffsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The topics property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.Topics.TopicsRequestBuilder Topics
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Item.Topics.TopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Item.WithSubjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/{subjectID}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Item.WithSubjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/{subjectID}", rawUrl)
        {
        }
        /// <summary>
        /// 获取条目
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.Subject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BangumiNet.Api.P1.Models.Subject?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BangumiNet.Api.P1.Models.Subject> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.P1.Models.Subject>(requestInfo, global::BangumiNet.Api.P1.Models.Subject.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取条目
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Subjects.Item.WithSubjectItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.P1.P1.Subjects.Item.WithSubjectItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.P1.P1.Subjects.Item.WithSubjectItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSubjectItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
