// <auto-generated/>
#nullable enable
using System.Runtime.Serialization;
using System;
namespace BangumiNet.Api.P1.P1.Privacy
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrivacyGetResponse_settings_follow
    {
        [EnumMember(Value = "all")]
        All,
        [EnumMember(Value = "none")]
        None,
    }
}
