// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.V0.V0.Users.Collections.Episodes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.V0.V0.Users.Collections.Episodes
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\users\-\collections\-\episodes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EpisodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BangumiNet.Api.V0.v0.users.collections.episodes.item collection</summary>
        /// <param name="position">章节 ID</param>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.Episodes.Item.WithEpisode_ItemRequestBuilder"/></returns>
        public global::BangumiNet.Api.V0.V0.Users.Collections.Episodes.Item.WithEpisode_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("episode_id", position);
                return new global::BangumiNet.Api.V0.V0.Users.Collections.Episodes.Item.WithEpisode_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.Episodes.EpisodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpisodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/-/collections/-/episodes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Collections.Episodes.EpisodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpisodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/-/collections/-/episodes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
