// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.Models;
using BangumiNet.Api.P1.P1.Blogs.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BangumiNet.Api.P1.P1.Blogs
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\blogs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlogsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The minus property</summary>
        public global::BangumiNet.Api.P1.P1.Blogs.Minus_RequestBuilder Minus
        {
            get => new global::BangumiNet.Api.P1.P1.Blogs.Minus_RequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>Gets an item from the BangumiNet.Api.P1.p1.blogs.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Blogs.Item.WithEntryItemRequestBuilder"/></returns>
        public global::BangumiNet.Api.P1.P1.Blogs.Item.WithEntryItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entryID", position);
                return new global::BangumiNet.Api.P1.P1.Blogs.Item.WithEntryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Blogs.BlogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlogsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/blogs", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Blogs.BlogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlogsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/blogs", rawUrl)
        {
        }

        /// <summary>
        /// 发布日志（type 固定为 1 日志），可携带标签、关联条目与已上传图片
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Blogs.BlogsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::BangumiNet.Api.P1.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::BangumiNet.Api.P1.P1.Blogs.BlogsPostResponse?> PostAsync(global::BangumiNet.Api.P1.P1.Blogs.BlogsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::BangumiNet.Api.P1.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BangumiNet.Api.P1.P1.Blogs.BlogsPostResponse>(requestInfo, global::BangumiNet.Api.P1.P1.Blogs.BlogsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// 发布日志（type 固定为 1 日志），可携带标签、关联条目与已上传图片
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPostRequestInformation(global::BangumiNet.Api.P1.P1.Blogs.BlogsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }

        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Blogs.BlogsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BangumiNet.Api.P1.P1.Blogs.BlogsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BangumiNet.Api.P1.P1.Blogs.BlogsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
