// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.V0.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IndexObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>deprecated, always false.</summary>
        [Obsolete("")]
        public bool? Ban { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>意义同&lt;a href=&quot;#model-Me&quot;&gt;Me&lt;/a&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.V0.Models.Creator? Creator { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.V0.Models.Creator Creator { get; set; }
#endif
        /// <summary>The desc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Desc { get; set; }
#nullable restore
#else
        public string Desc { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The nsfw property</summary>
        public bool? Nsfw { get; set; }
        /// <summary>目录评论及收藏数</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.V0.Models.Index_stat? Stat { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.V0.Models.Index_stat Stat { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>收录条目总数</summary>
        public int? Total { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.Models.IndexObject"/> and sets the default values.
        /// </summary>
        public IndexObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.IndexObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.V0.Models.IndexObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.V0.Models.IndexObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ban", n => { Ban = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Creator>(global::BangumiNet.Api.V0.Models.Creator.CreateFromDiscriminatorValue); } },
                { "desc", n => { Desc = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "nsfw", n => { Nsfw = n.GetBoolValue(); } },
                { "stat", n => { Stat = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Index_stat>(global::BangumiNet.Api.V0.Models.Index_stat.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ban", Ban);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Creator>("creator", Creator);
            writer.WriteStringValue("desc", Desc);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("nsfw", Nsfw);
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Index_stat>("stat", Stat);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("total", Total);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
