// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.V0.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Revision : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        public DateTimeOffset? CreatedAt { get; set; }

        /// <summary>意义同&lt;a href=&quot;#model-Me&quot;&gt;Me&lt;/a&gt;</summary>
        public global::BangumiNet.Api.V0.Models.Creator? Creator { get; set; }

        public int? Id { get; set; }

        public string? Summary { get; set; }

        public int? Type { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.Models.Revision"/> and sets the default values.
        /// </summary>
        public Revision()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.Revision"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.V0.Models.Revision CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.V0.Models.Revision();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Creator>(global::BangumiNet.Api.V0.Models.Creator.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Creator>("creator", Creator);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("summary", Summary);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
