// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.V0.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Subject_rating : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        public global::BangumiNet.Api.V0.Models.Subject_rating_count? Count { get; set; }

        public int? Rank { get; set; }

        public double? Score { get; set; }

        public int? Total { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.Models.Subject_rating"/> and sets the default values.
        /// </summary>
        public Subject_rating()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.Subject_rating"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.V0.Models.Subject_rating CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.V0.Models.Subject_rating();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "count", n => { Count = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Subject_rating_count>(global::BangumiNet.Api.V0.Models.Subject_rating_count.CreateFromDiscriminatorValue); } },
                { "rank", n => { Rank = n.GetIntValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Subject_rating_count>("count", Count);
            writer.WriteIntValue("rank", Rank);
            writer.WriteDoubleValue("score", Score);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
