// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.V0.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Subject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        public global::BangumiNet.Api.V0.Models.Subject_collection? Collection { get; set; }

        /// <summary>air date in `YYYY-MM-DD` format</summary>
        public string? Date { get; set; }

        /// <summary>由旧服务端从wiki中解析，对于书籍条目为`话数`</summary>
        public int? Eps { get; set; }

        public int? Id { get; set; }

        public global::BangumiNet.Api.V0.Models.Images? Images { get; set; }

        public List<global::BangumiNet.Api.V0.Models.Subjects>? Infobox { get; set; }

        public bool? Locked { get; set; }

        /// <summary>由维基人维护的 tag</summary>
        public List<string>? MetaTags { get; set; }

        public string? Name { get; set; }

        public string? NameCn { get; set; }

        public bool? Nsfw { get; set; }

        /// <summary>TV, Web, 欧美剧, DLC...</summary>
        public string? Platform { get; set; }

        public global::BangumiNet.Api.V0.Models.Subject_rating? Rating { get; set; }

        /// <summary>是否为书籍系列的主条目</summary>
        public bool? Series { get; set; }

        public string? Summary { get; set; }

        public List<global::BangumiNet.Api.V0.Models.Subjects>? Tags { get; set; }

        /// <summary>数据库中的章节数量</summary>
        public int? TotalEpisodes { get; set; }

        public int? Type { get; set; }

        /// <summary>书籍条目的册数，由旧服务端从wiki中解析</summary>
        public int? Volumes { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.Models.Subject"/> and sets the default values.
        /// </summary>
        public Subject()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.Models.Subject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.V0.Models.Subject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.V0.Models.Subject();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collection", n => { Collection = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Subject_collection>(global::BangumiNet.Api.V0.Models.Subject_collection.CreateFromDiscriminatorValue); } },
                { "date", n => { Date = n.GetStringValue(); } },
                { "eps", n => { Eps = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Images>(global::BangumiNet.Api.V0.Models.Images.CreateFromDiscriminatorValue); } },
                { "infobox", n => { Infobox = n.GetCollectionOfObjectValues<global::BangumiNet.Api.V0.Models.Subjects>(global::BangumiNet.Api.V0.Models.Subjects.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "meta_tags", n => { MetaTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "name_cn", n => { NameCn = n.GetStringValue(); } },
                { "nsfw", n => { Nsfw = n.GetBoolValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "rating", n => { Rating = n.GetObjectValue<global::BangumiNet.Api.V0.Models.Subject_rating>(global::BangumiNet.Api.V0.Models.Subject_rating.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetBoolValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::BangumiNet.Api.V0.Models.Subjects>(global::BangumiNet.Api.V0.Models.Subjects.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_episodes", n => { TotalEpisodes = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "volumes", n => { Volumes = n.GetIntValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Subject_collection>("collection", Collection);
            writer.WriteStringValue("date", Date);
            writer.WriteIntValue("eps", Eps);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Images>("images", Images);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.V0.Models.Subjects>("infobox", Infobox);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteCollectionOfPrimitiveValues<string>("meta_tags", MetaTags);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("name_cn", NameCn);
            writer.WriteBoolValue("nsfw", Nsfw);
            writer.WriteStringValue("platform", Platform);
            writer.WriteObjectValue<global::BangumiNet.Api.V0.Models.Subject_rating>("rating", Rating);
            writer.WriteBoolValue("series", Series);
            writer.WriteStringValue("summary", Summary);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.V0.Models.Subjects>("tags", Tags);
            writer.WriteIntValue("total_episodes", TotalEpisodes);
            writer.WriteIntValue("type", Type);
            writer.WriteIntValue("volumes", Volumes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
