// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.V0.V0.Users.Item.Collections.Characters;
using BangumiNet.Api.V0.V0.Users.Item.Collections.Persons;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.V0.V0.Users.Item.Collections
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\users\{username}\collections\-
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Minus_RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The characters property</summary>
        public global::BangumiNet.Api.V0.V0.Users.Item.Collections.Characters.CharactersRequestBuilder Characters
        {
            get => new global::BangumiNet.Api.V0.V0.Users.Item.Collections.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The persons property</summary>
        public global::BangumiNet.Api.V0.V0.Users.Item.Collections.Persons.PersonsRequestBuilder Persons
        {
            get => new global::BangumiNet.Api.V0.V0.Users.Item.Collections.Persons.PersonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Item.Collections.Minus_RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Minus_RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/{username}/collections/-", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Users.Item.Collections.Minus_RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Minus_RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/users/{username}/collections/-", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
