// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Wiki.Characters.Subjects.Revisions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Characters.Subjects
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\wiki\characters\-\subjects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The revisions property</summary>
        public global::BangumiNet.Api.P1.P1.Wiki.Characters.Subjects.Revisions.RevisionsRequestBuilder Revisions
        {
            get => new global::BangumiNet.Api.P1.P1.Wiki.Characters.Subjects.Revisions.RevisionsRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Characters.Subjects.SubjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/characters/-/subjects", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Characters.Subjects.SubjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/characters/-/subjects", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
