// <auto-generated/>
#nullable enable
using System.Runtime.Serialization;
using System;
namespace BangumiNet.Api.P1.P1.Turnstile
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetThemeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "dark")]
        #pragma warning disable CS1591
        Dark,
        #pragma warning restore CS1591
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
