// <auto-generated/>
#nullable enable
using System.Runtime.Serialization;
using System;
namespace BangumiNet.Api.P1.P1.Indexes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetOrderQueryParameterType
    {
        [EnumMember(Value = "hot")]
        Hot,
        [EnumMember(Value = "latest")]
        Latest,
    }
}
