// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BangumiNet.Api.P1.Models
{
    /// <summary>过滤模式  - all = 全站  - friends = 好友</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FilterMode
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "friends")]
        #pragma warning disable CS1591
        Friends,
        #pragma warning restore CS1591
    }
}
