// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HomeResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        /// <summary>The calendar property</summary>
        public global::BangumiNet.Api.P1.Models.Calendar? Calendar { get; set; }

        /// <summary>The famousGroups property</summary>
        public List<global::BangumiNet.Api.P1.Models.SlimGroup>? FamousGroups { get; set; }

        /// <summary>The groupTopics property</summary>
        public List<global::BangumiNet.Api.P1.Models.GroupTopic>? GroupTopics { get; set; }

        /// <summary>The hotSubjectTopics property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectTopic>? HotSubjectTopics { get; set; }

        /// <summary>The progress property</summary>
        public List<global::BangumiNet.Api.P1.Models.ProgressItem>? Progress { get; set; }

        /// <summary>The timeline property</summary>
        public List<global::BangumiNet.Api.P1.Models.Timeline>? Timeline { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.HomeResponse"/> and sets the default values.
        /// </summary>
        public HomeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.HomeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.HomeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.HomeResponse();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calendar", n => { Calendar = n.GetObjectValue<global::BangumiNet.Api.P1.Models.Calendar>(global::BangumiNet.Api.P1.Models.Calendar.CreateFromDiscriminatorValue); } },
                { "famousGroups", n => { FamousGroups = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimGroup>(global::BangumiNet.Api.P1.Models.SlimGroup.CreateFromDiscriminatorValue)?.AsList(); } },
                { "groupTopics", n => { GroupTopics = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.GroupTopic>(global::BangumiNet.Api.P1.Models.GroupTopic.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hotSubjectTopics", n => { HotSubjectTopics = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectTopic>(global::BangumiNet.Api.P1.Models.SubjectTopic.CreateFromDiscriminatorValue)?.AsList(); } },
                { "progress", n => { Progress = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.ProgressItem>(global::BangumiNet.Api.P1.Models.ProgressItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timeline", n => { Timeline = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Timeline>(global::BangumiNet.Api.P1.Models.Timeline.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.Calendar>("calendar", Calendar);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimGroup>("famousGroups", FamousGroups);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.GroupTopic>("groupTopics", GroupTopics);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectTopic>("hotSubjectTopics", HotSubjectTopics);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.ProgressItem>("progress", Progress);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Timeline>("timeline", Timeline);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
