// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::BangumiNet.Api.P1.Models.RaKuenCharacter"/>, <see cref="global::BangumiNet.Api.P1.Models.RaKuenEpisode"/>, <see cref="global::BangumiNet.Api.P1.Models.RaKuenGroupTopic"/>, <see cref="global::BangumiNet.Api.P1.Models.RaKuenPerson"/>, <see cref="global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RaKuenTopic : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::BangumiNet.Api.P1.Models.RaKuenCharacter"/></summary>
        public global::BangumiNet.Api.P1.Models.RaKuenCharacter? RaKuenCharacter { get; set; }

        /// <summary>Composed type representation for type <see cref="global::BangumiNet.Api.P1.Models.RaKuenEpisode"/></summary>
        public global::BangumiNet.Api.P1.Models.RaKuenEpisode? RaKuenEpisode { get; set; }

        /// <summary>Composed type representation for type <see cref="global::BangumiNet.Api.P1.Models.RaKuenGroupTopic"/></summary>
        public global::BangumiNet.Api.P1.Models.RaKuenGroupTopic? RaKuenGroupTopic { get; set; }

        /// <summary>Composed type representation for type <see cref="global::BangumiNet.Api.P1.Models.RaKuenPerson"/></summary>
        public global::BangumiNet.Api.P1.Models.RaKuenPerson? RaKuenPerson { get; set; }

        /// <summary>Composed type representation for type <see cref="global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic"/></summary>
        public global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic? RaKuenSubjectTopic { get; set; }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.RaKuenTopic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.RaKuenTopic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::BangumiNet.Api.P1.Models.RaKuenTopic();
            result.RaKuenCharacter = new global::BangumiNet.Api.P1.Models.RaKuenCharacter();
            result.RaKuenEpisode = new global::BangumiNet.Api.P1.Models.RaKuenEpisode();
            result.RaKuenGroupTopic = new global::BangumiNet.Api.P1.Models.RaKuenGroupTopic();
            result.RaKuenPerson = new global::BangumiNet.Api.P1.Models.RaKuenPerson();
            result.RaKuenSubjectTopic = new global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic();
            return result;
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RaKuenCharacter != null || RaKuenEpisode != null || RaKuenGroupTopic != null || RaKuenPerson != null || RaKuenSubjectTopic != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RaKuenCharacter, RaKuenEpisode, RaKuenGroupTopic, RaKuenPerson, RaKuenSubjectTopic);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.RaKuenCharacter>(null, RaKuenCharacter, RaKuenEpisode, RaKuenGroupTopic, RaKuenPerson, RaKuenSubjectTopic);
        }
    }
}
#pragma warning restore CS0618
