// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RaKuenSubjectTopic : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        /// <summary>The creator property</summary>
        public global::BangumiNet.Api.P1.Models.SlimUser? Creator { get; set; }

        /// <summary>The id property</summary>
        public int? Id { get; set; }

        /// <summary>The replyCount property</summary>
        public int? ReplyCount { get; set; }

        /// <summary>The subject property</summary>
        public global::BangumiNet.Api.P1.Models.SlimSubject? Subject { get; set; }

        /// <summary>The title property</summary>
        public string? Title { get; set; }

        /// <summary>The type property</summary>
        public global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic_type? Type { get; set; }

        /// <summary>最后回复时间，unix time stamp in seconds</summary>
        public int? UpdatedAt { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic"/> and sets the default values.
        /// </summary>
        public RaKuenSubjectTopic()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creator", n => { Creator = n.GetObjectValue<global::BangumiNet.Api.P1.Models.SlimUser>(global::BangumiNet.Api.P1.Models.SlimUser.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "replyCount", n => { ReplyCount = n.GetIntValue(); } },
                { "subject", n => { Subject = n.GetObjectValue<global::BangumiNet.Api.P1.Models.SlimSubject>(global::BangumiNet.Api.P1.Models.SlimSubject.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic_type>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetIntValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.SlimUser>("creator", Creator);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("replyCount", ReplyCount);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.SlimSubject>("subject", Subject);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::BangumiNet.Api.P1.Models.RaKuenSubjectTopic_type>("type", Type);
            writer.WriteIntValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
