// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubjectHomeResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        /// <summary>The characters property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectCharacter>? Characters { get; set; }

        /// <summary>The comments property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectInterestComment>? Comments { get; set; }

        /// <summary>The episodes property</summary>
        public List<global::BangumiNet.Api.P1.Models.Episode>? Episodes { get; set; }

        /// <summary>The indexes property</summary>
        public List<global::BangumiNet.Api.P1.Models.SlimIndex>? Indexes { get; set; }

        /// <summary>The recs property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectRec>? Recs { get; set; }

        /// <summary>The relations property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectRelation>? Relations { get; set; }

        /// <summary>The reviews property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectReview>? Reviews { get; set; }

        /// <summary>The staff property</summary>
        public List<global::BangumiNet.Api.P1.Models.SubjectStaff>? Staff { get; set; }

        /// <summary>The subject property</summary>
        public global::BangumiNet.Api.P1.Models.Subject? Subject { get; set; }

        /// <summary>The topics property</summary>
        public List<global::BangumiNet.Api.P1.Models.Topic>? Topics { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.SubjectHomeResponse"/> and sets the default values.
        /// </summary>
        public SubjectHomeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.SubjectHomeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.SubjectHomeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.SubjectHomeResponse();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "characters", n => { Characters = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectCharacter>(global::BangumiNet.Api.P1.Models.SubjectCharacter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "comments", n => { Comments = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectInterestComment>(global::BangumiNet.Api.P1.Models.SubjectInterestComment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "episodes", n => { Episodes = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Episode>(global::BangumiNet.Api.P1.Models.Episode.CreateFromDiscriminatorValue)?.AsList(); } },
                { "indexes", n => { Indexes = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimIndex>(global::BangumiNet.Api.P1.Models.SlimIndex.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recs", n => { Recs = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectRec>(global::BangumiNet.Api.P1.Models.SubjectRec.CreateFromDiscriminatorValue)?.AsList(); } },
                { "relations", n => { Relations = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectRelation>(global::BangumiNet.Api.P1.Models.SubjectRelation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reviews", n => { Reviews = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectReview>(global::BangumiNet.Api.P1.Models.SubjectReview.CreateFromDiscriminatorValue)?.AsList(); } },
                { "staff", n => { Staff = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectStaff>(global::BangumiNet.Api.P1.Models.SubjectStaff.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetObjectValue<global::BangumiNet.Api.P1.Models.Subject>(global::BangumiNet.Api.P1.Models.Subject.CreateFromDiscriminatorValue); } },
                { "topics", n => { Topics = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Topic>(global::BangumiNet.Api.P1.Models.Topic.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectCharacter>("characters", Characters);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectInterestComment>("comments", Comments);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Episode>("episodes", Episodes);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimIndex>("indexes", Indexes);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectRec>("recs", Recs);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectRelation>("relations", Relations);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectReview>("reviews", Reviews);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SubjectStaff>("staff", Staff);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.Subject>("subject", Subject);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Topic>("topics", Topics);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
