// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubjectPlatform : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        public string? Alias { get; set; }

        public bool? EnableHeader { get; set; }

        public int? Id { get; set; }

        public int? Order { get; set; }

        public string? SearchString { get; set; }

        public List<string>? SortKeys { get; set; }

        public string? Type { get; set; }

        public string? TypeCN { get; set; }

        public string? WikiTpl { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.SubjectPlatform"/> and sets the default values.
        /// </summary>
        public SubjectPlatform()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.SubjectPlatform"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.SubjectPlatform CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.SubjectPlatform();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "enableHeader", n => { EnableHeader = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "searchString", n => { SearchString = n.GetStringValue(); } },
                { "sortKeys", n => { SortKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "typeCN", n => { TypeCN = n.GetStringValue(); } },
                { "wikiTpl", n => { WikiTpl = n.GetStringValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteBoolValue("enableHeader", EnableHeader);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("searchString", SearchString);
            writer.WriteCollectionOfPrimitiveValues<string>("sortKeys", SortKeys);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("typeCN", TypeCN);
            writer.WriteStringValue("wikiTpl", WikiTpl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
