// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubjectTopic : global::BangumiNet.Api.P1.Models.Topic, IParsable
    {

        public List<global::BangumiNet.Api.P1.Models.Reply>? Replies { get; set; }

        public global::BangumiNet.Api.P1.Models.SlimSubject? Subject { get; set; }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.SubjectTopic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::BangumiNet.Api.P1.Models.SubjectTopic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.SubjectTopic();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "replies", n => { Replies = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Reply>(global::BangumiNet.Api.P1.Models.Reply.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetObjectValue<global::BangumiNet.Api.P1.Models.SlimSubject>(global::BangumiNet.Api.P1.Models.SlimSubject.CreateFromDiscriminatorValue); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.Reply>("replies", Replies);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.SlimSubject>("subject", Subject);
        }
    }
}
#pragma warning restore CS0618
