// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimelineMemo_mono : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }

        public List<global::BangumiNet.Api.P1.Models.SlimCharacter>? Characters { get; set; }

        public List<global::BangumiNet.Api.P1.Models.SlimPerson>? Persons { get; set; }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.TimelineMemo_mono"/> and sets the default values.
        /// </summary>
        public TimelineMemo_mono()
        {
            AdditionalData = new Dictionary<string, object>();
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.TimelineMemo_mono"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.TimelineMemo_mono CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.TimelineMemo_mono();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "characters", n => { Characters = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimCharacter>(global::BangumiNet.Api.P1.Models.SlimCharacter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "persons", n => { Persons = n.GetCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimPerson>(global::BangumiNet.Api.P1.Models.SlimPerson.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimCharacter>("characters", Characters);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.P1.Models.SlimPerson>("persons", Persons);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
