// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.P1.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blog property</summary>
        public int? Blog { get; set; }
        /// <summary>The friend property</summary>
        public int? Friend { get; set; }
        /// <summary>The group property</summary>
        public int? Group { get; set; }
        /// <summary>The index property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.P1.Models.UserIndexStats? Index { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.P1.Models.UserIndexStats Index { get; set; }
#endif
        /// <summary>The mono property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.P1.Models.UserMonoCollectionStats? Mono { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.P1.Models.UserMonoCollectionStats Mono { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BangumiNet.Api.P1.Models.UserSubjectCollectionStats? Subject { get; set; }
#nullable restore
#else
        public global::BangumiNet.Api.P1.Models.UserSubjectCollectionStats Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.Models.UserStats"/> and sets the default values.
        /// </summary>
        public UserStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.Models.UserStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.P1.Models.UserStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.P1.Models.UserStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blog", n => { Blog = n.GetIntValue(); } },
                { "friend", n => { Friend = n.GetIntValue(); } },
                { "group", n => { Group = n.GetIntValue(); } },
                { "index", n => { Index = n.GetObjectValue<global::BangumiNet.Api.P1.Models.UserIndexStats>(global::BangumiNet.Api.P1.Models.UserIndexStats.CreateFromDiscriminatorValue); } },
                { "mono", n => { Mono = n.GetObjectValue<global::BangumiNet.Api.P1.Models.UserMonoCollectionStats>(global::BangumiNet.Api.P1.Models.UserMonoCollectionStats.CreateFromDiscriminatorValue); } },
                { "subject", n => { Subject = n.GetObjectValue<global::BangumiNet.Api.P1.Models.UserSubjectCollectionStats>(global::BangumiNet.Api.P1.Models.UserSubjectCollectionStats.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("blog", Blog);
            writer.WriteIntValue("friend", Friend);
            writer.WriteIntValue("group", Group);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.UserIndexStats>("index", Index);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.UserMonoCollectionStats>("mono", Mono);
            writer.WriteObjectValue<global::BangumiNet.Api.P1.Models.UserSubjectCollectionStats>("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
