// <auto-generated/>
#nullable enable
using System.Runtime.Serialization;
using System;
namespace BangumiNet.Api.P1.Models
{
    /// <summary>用户时光机板块</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserHomepageSection
    {
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "game")]
        Game,
        [EnumMember(Value = "book")]
        Book,
        [EnumMember(Value = "music")]
        Music,
        [EnumMember(Value = "real")]
        Real,
        [EnumMember(Value = "mono")]
        Mono,
        [EnumMember(Value = "blog")]
        Blog,
        [EnumMember(Value = "friend")]
        Friend,
        [EnumMember(Value = "group")]
        Group,
        [EnumMember(Value = "index")]
        Index,
    }
}
