// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Wiki.Persons.Revisions
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\wiki\persons\-\revisions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RevisionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BangumiNet.Api.P1.p1.wiki.persons.revisions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.Item.WithRevisionItemRequestBuilder"/></returns>
        public global::BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.Item.WithRevisionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("revisionID", position);
                return new global::BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.Item.WithRevisionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.RevisionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevisionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/persons/-/revisions", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Wiki.Persons.Revisions.RevisionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevisionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/wiki/persons/-/revisions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
