// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.V0.V0.Search.Subjects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubjectsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>不同条件之间是 `且` 的关系</summary>
        public global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_filter? Filter { get; set; }
        /// <summary>The keyword property</summary>
        public string? Keyword { get; set; }
        /// <summary>排序规则- `match` meilisearch 的默认排序，按照匹配程度- `heat` 收藏人数- `rank` 排名由高到低- `score` 评分</summary>
        public global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_sort? Sort { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody"/> and sets the default values.
        /// </summary>
        public SubjectsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Sort = global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_sort.Match;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filter", n => { Filter = n.GetObjectValue<global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_filter>(global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_filter.CreateFromDiscriminatorValue); } },
                { "keyword", n => { Keyword = n.GetStringValue(); } },
                { "sort", n => { Sort = n.GetEnumValue<global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_sort>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_filter>("filter", Filter);
            writer.WriteStringValue("keyword", Keyword);
            writer.WriteEnumValue<global::BangumiNet.Api.V0.V0.Search.Subjects.SubjectsPostRequestBody_sort>("sort", Sort);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
