// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Subjects.Collects;
using BangumiNet.Api.P1.P1.Subjects.Posts;
using BangumiNet.Api.P1.P1.Subjects.Topics;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Subjects
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\subjects\-
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Minus_RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collects property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Collects.CollectsRequestBuilder Collects
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Collects.CollectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Posts.PostsRequestBuilder Posts
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The topics property</summary>
        public global::BangumiNet.Api.P1.P1.Subjects.Topics.TopicsRequestBuilder Topics
        {
            get => new global::BangumiNet.Api.P1.P1.Subjects.Topics.TopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Minus_RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Minus_RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/-", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Subjects.Minus_RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Minus_RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/subjects/-", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
