// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.Legacy.Models
{
    /// <summary>
    /// 别名（另外添加出来的 key 为 0 开始的数字）
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Legacy_MonoInfo_alias : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>日文名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Jp { get; set; }
#nullable restore
#else
        public string Jp { get; set; }
#endif
        /// <summary>纯假名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kana { get; set; }
#nullable restore
#else
        public string Kana { get; set; }
#endif
        /// <summary>昵称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nick { get; set; }
#nullable restore
#else
        public string Nick { get; set; }
#endif
        /// <summary>罗马字</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Romaji { get; set; }
#nullable restore
#else
        public string Romaji { get; set; }
#endif
        /// <summary>第二中文名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zh { get; set; }
#nullable restore
#else
        public string Zh { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo_alias"/> and sets the default values.
        /// </summary>
        public Legacy_MonoInfo_alias()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo_alias"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo_alias CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo_alias();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "jp", n => { Jp = n.GetStringValue(); } },
                { "kana", n => { Kana = n.GetStringValue(); } },
                { "nick", n => { Nick = n.GetStringValue(); } },
                { "romaji", n => { Romaji = n.GetStringValue(); } },
                { "zh", n => { Zh = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("jp", Jp);
            writer.WriteStringValue("kana", Kana);
            writer.WriteStringValue("nick", Nick);
            writer.WriteStringValue("romaji", Romaji);
            writer.WriteStringValue("zh", Zh);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
