// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BangumiNet.Api.Legacy.Models
{
    /// <summary>
    /// 虚拟角色
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Legacy_Character : global::BangumiNet.Api.Legacy.Models.Legacy_Mono, IParsable
    {
        /// <summary>声优列表</summary>
        public List<global::BangumiNet.Api.Legacy.Models.Legacy_MonoBase>? Actors { get; set; }
        /// <summary>人物信息</summary>
        public global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo? Info { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BangumiNet.Api.Legacy.Models.Legacy_Character"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::BangumiNet.Api.Legacy.Models.Legacy_Character CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BangumiNet.Api.Legacy.Models.Legacy_Character();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "actors", n => { Actors = n.GetCollectionOfObjectValues<global::BangumiNet.Api.Legacy.Models.Legacy_MonoBase>(global::BangumiNet.Api.Legacy.Models.Legacy_MonoBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "info", n => { Info = n.GetObjectValue<global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo>(global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::BangumiNet.Api.Legacy.Models.Legacy_MonoBase>("actors", Actors);
            writer.WriteObjectValue<global::BangumiNet.Api.Legacy.Models.Legacy_MonoInfo>("info", Info);
        }
    }
}
#pragma warning restore CS0618
