// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using BangumiNet.Api.P1.P1.Passkey.Login.Options;
using BangumiNet.Api.P1.P1.Passkey.Login.Verify;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.P1.P1.Passkey.Login
{
    /// <summary>
    /// Builds and executes requests for operations under \p1\passkey\login
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The optionsPath property</summary>
        public global::BangumiNet.Api.P1.P1.Passkey.Login.Options.OptionsRequestBuilder OptionsPath
        {
            get => new global::BangumiNet.Api.P1.P1.Passkey.Login.Options.OptionsRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The verify property</summary>
        public global::BangumiNet.Api.P1.P1.Passkey.Login.Verify.VerifyRequestBuilder Verify
        {
            get => new global::BangumiNet.Api.P1.P1.Passkey.Login.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Passkey.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/passkey/login", pathParameters)
        {
        }

        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.P1.P1.Passkey.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/p1/passkey/login", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
