// <auto-generated/>
#pragma warning disable CS0618
using BangumiNet.Api.V0.V0.Persons.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiNet.Api.V0.V0.Persons
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\persons
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PersonsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BangumiNet.Api.V0.v0.persons.item collection</summary>
        /// <param name="position">人物 ID</param>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder"/></returns>
        public global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("person_id", position);
                return new global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BangumiNet.Api.V0.v0.persons.item collection</summary>
        /// <param name="position">人物 ID</param>
        /// <returns>A <see cref="global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("person_id", position);
                return new global::BangumiNet.Api.V0.V0.Persons.Item.WithPerson_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Persons.PersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/persons", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiNet.Api.V0.V0.Persons.PersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/persons", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
