name: Test & Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Test
        run: dotnet test -c Release

      - name: Build
        run: dotnet build BangumiNet -c Release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-archive
          path: BangumiNet*/bin/Release/*/
